version: "3.7"

services:
  mysql:
    image: cir-cn.chp.belastingdienst.nl/external/bitnami/mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  mysql-data:
