name: hrm

services:

  people-service:
    build: .
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9080/health/ready" ]
      interval: 2s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "9080:9080"
    environment:
      MYSQL_HOSTNAME: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "people-db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USE_SSL: "true"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hrm-network

  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "people-db"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      start_period: 2s
      retries: 10
    networks:
      - hrm-network

volumes:
  mysql-data:

networks:
  hrm-network:
    driver: bridge
